// external/web-dogfood-sources/vite-vue-counter.vue
<!-- Reviewed boundary derived from the MIT-licensed create-vite Vue template. -->
<!-- Upstream remains read-only; this reduced fixture preserves only the counter state transition. -->
<script setup>
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <button type="button" @click="count++">count is {{ count }}</button>
</template>

// external/web-dogfood-sources/vite-react-counter.jsx
// Reviewed boundary derived from the MIT-licensed create-vite React template.
// Upstream remains read-only; this reduced fixture preserves only the counter state transition.
import { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)

  return (
    <button type="button" onClick={() => setCount((value) => value + 1)}>
      count is {count}
    </button>
  )
}
